title = "Chris Haines - SEO Consultant"
logo = "/img/chris-haines-logo.png"
description = "Chris Haines is an SEO Consultant with over 10 years experience"
copyright = "&copy; 2023 Chris Haines. All Rights Reserved."

dateFormat = "2 January 2006"

[author]
  name = "Chris Haines"
  image = "img/chris2.png"
  headline = "Not your ordinary theme!"
  bio = "Chris is an SEO consultant and has been working in SEO for over 10 years. When not involved in SEO Chris enjoys messing around with vintage synthesizers."
  links = [
    { twitter = "https://twitter.com/chris_at_b449" },
    { linkedin = "https://uk.linkedin.com/in/london-seo-consultant-chris-haines" },
    { youtube = "https://youtube.com/" },
  ]
