languageCode = "en"
languageName = "English (UK)"
displayName = ":flag-en:"
isoCode = "en"
weight = 1
rtl = false

title = "Chris Haines"
# logo = "https://i.ibb.co/PhZ1yzF/chris-haines-seo-logo.webp"
description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
copyright = "&copy; 2022 Chris Haines"

dateFormat = "2 January 2006"

[author]
  name = "Chris Haines"
  image = "/images/author2.png"
  headline = "Not your ordinary theme!"
  bio = "This is an example author bio, and although there's a stock photo of a dog here, this article was actually created by a human. :dog:"
  links = [
    { twitter = "https://twitter.com/" },
    { facebook = "https://facebook.com/" },
    { linkedin = "https://linkedin.com/" },
    { youtube = "https://youtube.com/" },
  ]
