# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.


[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "About"
  pageRef = "About"
  weight = 20

[[main]]
  name = "SEO Training"
  pageRef = "seo-training"
  weight = 30

[[main]]
  name = "SEO Services"
  pageRef = "seo-services"
  weight = 40

[[main]]
  name = "Tools"
  pageRef = "tools"
  weight = 50

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 60

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

  [[footer]]
  name = "SEO Services"
  idnentifier = "SEO Services"
  pageRef = "seo-services"
  weight = 20

  [[footer]]
  name = "Links"
  pageRef = "links"
  parent = "SEO Services"
  weight = 20

[[footer]]
  name = "SEO Consultant London"
  pageRef = "seo-consultant-london"
  weight = 30

[[footer]]
  name = "Privacy Policy"
  pageRef = "privacy-policy"
  weight = 40

