---
label: Front matter template
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: text
  name: description
  label: description
- type: text
  name: slug
  label: slug
- type: list
  name: tags
  label: tags
pages:
- content/blog/alternative-search-engines-are-they-worth-it.md
- content/blog/best-cafes-to-work-in-london.md
- content/blog/how-far-are-we-away-from-her-is-this-the-future-of-search.md
- content/blog/tfl-hack.md
- content/blog/why-i-gave-up-on-wordpress-and-what-i-switched-to.md
